In [2]:
import pandas as pd
import numpy as np

In [3]:
# wrong comparison:
np.nan == np.nan

False

In [4]:
# right comparison:
np.nan is np.nan

True

In [5]:
df = pd.read_csv("movie_scores.csv")
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [6]:
# Returning NaN values as False:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [7]:
# Show the data that pre_movie_score is not NaN:
df[df["pre_movie_score"].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [8]:
#(1): KEEP DATA: we just keep data as it is.

In [9]:
#(2): DROP DATA: deleting NaN data:

In [10]:
# Deleting rows that contains NaN:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [11]:
# Keeping the rows that at has 2 values at least, delete others: 
df.dropna(thresh=2)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [12]:
# Deleting NaN according to the columns:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [14]:
# If last_name is NaN delete its row:
df.dropna(subset=["last_name"])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [15]:
#(3): REPLACE DATA: fill data with proper data:

In [17]:
# Filling with zero:
df["pre_movie_score"] = df["pre_movie_score"].fillna(0)
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               NaN
2       Hugh   Jackman  51.0    m              0.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [24]:
# Filling with mean:
df = pd.read_csv("movie_scores.csv")

df["pre_movie_score"] = df["pre_movie_score"].fillna(df["pre_movie_score"].mean())
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [25]:
# Filling all numeric columns with mean of that column automaticly:
df = pd.read_csv("movie_scores.csv")

df.fillna(df.mean())

C:\Users\Taha\AppData\Local\Temp\ipykernel_6284\3539755089.py:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())

  first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1        NaN       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0