In [2]:
# For DF that aren't in the exact same orders we use 'merge'

In [84]:
import pandas as pd

In [85]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [86]:
registrations

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [87]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [88]:
# inner merge:
pd.merge(registrations,logins,how="inner",on="name")

   reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4

In [89]:
# left merge (order is important):
pd.merge(registrations,logins,how="left",on="name")

   reg_id    name  log_id
0       1  Andrew     2.0
1       2    Bobo     4.0
2       3  Claire     NaN
3       4   David     NaN

In [90]:
# right merge (order is important):
pd.merge(registrations,logins,how="right",on="name")

   reg_id     name  log_id
0     NaN   Xavier       1
1     1.0   Andrew       2
2     NaN  Yolanda       3
3     2.0     Bobo       4

In [91]:
# outer merge:
pd.merge(registrations,logins,how="outer",on="name")

   reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0     Bobo     4.0
2     3.0   Claire     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0

In [92]:
registrations = registrations.set_index("name")

In [93]:
registrations

        reg_id
name
Andrew       1
Bobo         2
Claire       3
David        4

In [94]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [95]:
# advance selecting the column (on) or index for adding df:
pd.merge(registrations,logins, how="inner", left_index=True, right_on="name")

   reg_id  log_id    name
1       1       2  Andrew
3       2       4    Bobo

In [96]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [97]:
registrations

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [98]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [99]:
registrations = registrations.rename(columns={"name": "reg_name"})

In [100]:
registrations

   reg_id reg_name
0       1   Andrew
1       2     Bobo
2       3   Claire
3       4    David

In [101]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [102]:
# advance selecting the column (on) or index for adding df:
result = pd.merge(registrations,logins,how="inner",left_on="reg_name",right_on="name")

In [103]:
result

   reg_id reg_name  log_id    name
0       1   Andrew       2  Andrew
1       2     Bobo       4    Bobo

In [104]:
# drop the extra column for names:
result = result.drop("reg_name", axis=1)

In [105]:
result

   reg_id  log_id    name
0       1       2  Andrew
1       2       4    Bobo

In [106]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [107]:
registrations

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [108]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [111]:
registrations = registrations.rename(columns={"reg_id": "id"})
logins = logins.rename(columns={"log_id": "id"})

In [112]:
registrations

   id    name
0   1  Andrew
1   2    Bobo
2   3  Claire
3   4   David

In [113]:
logins

   id     name
0   1   Xavier
1   2   Andrew
2   3  Yolanda
3   4     Bobo

In [114]:
# pandas automatically distinguish two columns with the same name:
pd.merge(registrations,logins,how="inner",on="name")

   id_x    name  id_y
0     1  Andrew     2
1     2    Bobo     4

In [115]:
# how to customize the names of the columns with the same names (replace the _x and _y with our own amounts):
pd.merge(registrations,logins,how="inner",on="name", suffixes=("_reg","_log"))

   id_reg    name  id_log
0       1  Andrew       2
1       2    Bobo       4