In [1]:
import pandas as pd
from datetime import datetime

In [2]:
# reviewing datetime:
my_year = 2016
my_mon = 3
my_day = 7
my_hour = 14
my_min = 12
my_sec = 5

In [3]:
mydate = datetime(my_year,my_mon,my_day,my_hour,my_min,my_sec)

In [4]:
mydate

datetime.datetime(2016, 3, 7, 14, 12, 5)

In [5]:
# the usage is calling some info such as .year easily:
mydate.year

2016

###### How pandas works with datetime object:

In [6]:
my_ser = pd.Series(["Nov3, 1990", "2000,01,01", None])

In [7]:
my_ser

0    Nov3, 1990
1    2000,01,01
2          None
dtype: object

In [9]:
# It is not gonna work so we have to change it to date object:
my_ser.year

AttributeError: 'Series' object has no attribute 'year'

###### changing Series to the datetime object:

In [17]:
my_ser = pd.to_datetime(my_ser)

In [18]:
my_ser

0   1990-11-03
1   2000-01-01
2          NaT
dtype: datetime64[ns]

In [19]:
my_ser[0]

Timestamp('1990-11-03 00:00:00')

In [20]:
my_ser[0].year

1990

###### Dealing with European and Americane date style:

In [24]:
# Americane stryle (default): (month-day-year)
# How to convert to European style (day-month-year):
euro_date = "10-12-2000"

# This is not what we want (10 shuld be day):
pd.to_datetime(euro_date)

Timestamp('2000-10-12 00:00:00')

In [25]:
# Fixing the problem:
pd.to_datetime(euro_date,dayfirst=True)

Timestamp('2000-12-10 00:00:00')

###### Dealing with custome style date:

In [28]:
style_date = "12--Dec--2000"

In [31]:
# How help pandas to understand that is a datetime and avoiding error:
pd.to_datetime(style_date, format="%d--%b--%Y")

Timestamp('2000-12-12 00:00:00')

###### Pandas is flexible for understanding standard formats of date:

In [34]:
standard_date = "12th of Dec 2000"

In [35]:
pd.to_datetime(standard_date)

Timestamp('2000-12-12 00:00:00')

###### 2 ways to convert Series from csv file to datetime dtype:

In [43]:
# First way:
sales = pd.read_csv("RetailSales_BeerWineLiquor.csv")
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [46]:
# Checking DATE Series dtype:
sales["DATE"]

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: object

In [51]:
# changing the DATE Series dtype to datetime:
sales["DATE"] = pd.to_datetime(sales["DATE"])
sales["DATE"]

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [54]:
# Second way (faster way):
sales = pd.read_csv("RetailSales_BeerWineLiquor.csv", parse_dates=[0])
sales["DATE"]

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

###### resample:

In [60]:
# It is groupby that works with date:
sales = pd.read_csv("RetailSales_BeerWineLiquor.csv", parse_dates=[0])
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [61]:
sales = sales.set_index("DATE")
sales

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [62]:
sales.resample(rule="A").mean()

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

###### datetime attributes:

In [65]:
sales = pd.read_csv("RetailSales_BeerWineLiquor.csv", parse_dates=[0])
sales.head()

        DATE  MRTSSM4453USN
0 1992-01-01           1509
1 1992-02-01           1541
2 1992-03-01           1597
3 1992-04-01           1675
4 1992-05-01           1822

In [66]:
sales["DATE"]

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [67]:
# with (.dt) we can work with datetime attributes: 
sales["DATE"].dt.year

0      1992
1      1992
2      1992
3      1992
4      1992
       ...
335    2019
336    2020
337    2020
338    2020
339    2020
Name: DATE, Length: 340, dtype: int64

In [68]:
sales["DATE"].dt.month

0       1
1       2
2       3
3       4
4       5
       ..
335    12
336     1
337     2
338     3
339     4
Name: DATE, Length: 340, dtype: int64